### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'solutions'

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipBLASLt#619]
Please see the details

```
[...]
# Found  hipcc version 6.0.32830-d62f6a171
Tensile::WARNING: Global parameter AsmDebug = False unrecognised.
# CodeObjectVersion from TensileCreateLibrary: default
# CxxCompiler       from TensileCreateLibrary: hipcc
# Architecture      from TensileCreateLibrary: gfx908:xnack+_gfx908:xnack-
# LibraryFormat     from TensileCreateLibrary: msgpack
# LibraryLogicFiles:
Reading logic files: Launching 32 threads...
Reading logic files: Done. (0.0 secs elapsed)
Traceback (most recent call last):
  File "/usr/local/src/hipBLASLt/build/release/library/../virtualenv/lib/python3.10/site-packages/Tensile/bin/TensileCreateLibrary", line 43, in <module>
    TensileCreateLibrary()
  File "/usr/local/src/hipBLASLt/build/release/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 60, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/src/hipBLASLt/build/release/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 1357, in TensileCreateLibrary
    solutions, masterLibraries, fullMasterLibrary = generateLogicDataAndSolutions(logicFiles, args)
  File "/usr/local/src/hipBLASLt/build/release/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 60, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/src/hipBLASLt/build/release/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 1125, in generateLogicDataAndSolutions
    solutions = [sol.originalSolution for _, sol in fullMasterLibrary.solutions.items()]
AttributeError: 'NoneType' object has no attribute 'solutions'
make[2]: *** [library/CMakeFiles/TENSILE_LIBRARY_TARGET.dir/build.make:74: Tensile/library/TensileManifest.txt] Error 1
make[2]: Leaving directory '/usr/local/src/hipBLASLt/build/release'
make[1]: *** [CMakeFiles/Makefile2:272: library/CMakeFiles/TENSILE_LIBRARY_TARGET.dir/all] Error 2
make[1]: Leaving directory '/usr/local/src/hipBLASLt/build/release'
make: *** [Makefile:166: all] Error 2
+ check_exit_code 2
+ ((  2 != 0  ))
+ exit 2
```

**Comment by IMbackK** [comment]
MI100 is not supported, pointlessly, as a 3rd party opened a pr that adds support for this architecture (and really the isa differences between gfx908 and gfx90a are tiny anyhow), yet they just dont merge it:
https://github.com/ROCm/hipBLASLt/pull/327

**Comment by jinz2014** [comment]
Thanks for your answer.

**Comment by ppanchad-amd** [comment]
@jinz2014 Will check with internal team if they will add support for GFX 908 and let you know. Thanks!

**Comment by IMbackK** [comment]
uh clearly they are working on it https://github.com/ROCm/hipBLASLt/pull/327
(branch was recently rebased)

**Comment by IMbackK** [comment]
@ppanchad-amd  Since gfx908 suport has landed in develop you can close this issue

**Comment by jinz2014** [comment]
@ppanchad-amd  

gfx908 may be added to hardware list below.  Thanks.

Requirements
To install hipBLASLt, you must meet the following requirements:

Required hardware:

gfx90a card
gfx94x card
gfx110x card
